# Generated by Django 4.2.3 on 2023-08-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('industry_type', models.CharField(max_length=255)),
                ('number_of_openings', models.PositiveSmallIntegerField()),
                ('employment_type', models.CharField(max_length=50)),
                ('duration_of_employment', models.IntegerField(blank=True, null=True)),
                ('open_until', models.DateField()),
                ('is_active', models.BooleanField()),
                ('salary_visible', models.BooleanField()),
                ('min_salary', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_salary', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrers.joblocation')),
                ('skills_mandatory', models.ManyToManyField(related_name='mandatory_skill_jobs', to='carrers.skill')),
                ('skills_optional', models.ManyToManyField(related_name='optional_skills_jobs', to='carrers.skill')),
            ],
        ),
    ]
