# Generated by Django 4.2.3 on 2023-08-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0002_alter_job_created_on_alter_job_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills_optional',
            field=models.ManyToManyField(blank=True, null=True, related_name='optional_skills_jobs', to='carrers.skill'),
        ),
    ]
