# Generated by Django 4.2.3 on 2023-08-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0003_alter_job_skills_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration_of_employment',
        ),
        migrations.AddField(
            model_name='job',
            name='duration_of_employment_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_level',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('mba', 'MBA'), ('ms', 'MS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('work_from_home', 'Work from Home')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrers.joblocation'),
        ),
    ]
