# Generated by Django 4.2.3 on 2023-08-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0005_alter_job_skills_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='job',
            name='open_until',
        ),
    ]
