# Generated by Django 4.2.3 on 2023-08-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0006_remove_job_created_on_remove_job_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration_of_employment_months',
        ),
        migrations.RemoveField(
            model_name='job',
            name='number_of_openings',
        ),
        migrations.AddField(
            model_name='job',
            name='company_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrers.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='duration_in_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrers.joblocation'),
        ),
        migrations.AddField(
            model_name='job',
            name='no_of_openings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='valid_until',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_visible',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_mandatory',
            field=models.ManyToManyField(related_name='jobs_mandatory', to='carrers.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_optional',
            field=models.ManyToManyField(related_name='jobs_optional', to='carrers.skill'),
        ),
    ]
