# Generated by Django 4.2.3 on 2023-08-15 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0007_remove_job_duration_of_employment_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrers.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrers.joblocation'),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_openings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
