# Generated by Django 4.2.3 on 2023-08-15 05:07

from django.db import migrations, models
import django.db.models.deletion



def set_default_company(apps, schema_editor):
    Company = apps.get_model('carrers', 'Company')
    Job = apps.get_model('carrers', 'Job')

    default_company_id = 1  # You can change this to the appropriate default company ID

    default_company = Company.objects.get(pk=default_company_id)

    Job.objects.update(company_info=default_company)


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0008_alter_job_company_info_alter_job_created_on_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_company),
        migrations.AlterField(
            model_name='job',
            name='company_info',
            field=models.ForeignKey(default=1, on_delete=models.deletion.CASCADE, to='carrers.company'),
            preserve_default=False,
        ),
    ]
