# Generated by Django 4.2.3 on 2023-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0010_set_default_company_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
