# Generated by Django 4.2.3 on 2023-08-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0012_alter_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration_in_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_openings',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
